definitions:
  domain.GitlabProject:
    properties:
      description:
        type: string
      mergeRequestsEnabled:
        type: boolean
      name:
        type: string
      snippetsEnabled:
        type: boolean
      visibility:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /v1/git/group:
    post:
      consumes:
      - application/json
      description: Create Group of git
      produces:
      - application/json
      responses: {}
      summary: CreateGroup
      tags:
      - GitGroup
  /v1/git/project:
    post:
      consumes:
      - application/json
      description: Create Project for gitlab
      parameters:
      - description: body for CreateProject content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.GitlabProject'
      produces:
      - application/json
      responses: {}
      summary: CreateProject
      tags:
      - GitProject
  /v1/project:
    post:
      consumes:
      - application/json
      description: create project
      produces:
      - application/json
      responses: {}
      summary: create project
      tags:
      - Project
  /v1/project/deleteFiles:
    delete:
      consumes:
      - multipart/form-data
      description: DeleteFiles
      parameters:
      - description: id for project
        in: query
        name: project_id
        required: true
        type: string
      - description: file url
        in: query
        name: fileurl
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: DeleteFiles
      tags:
      - Project
  /v1/project/likeCount:
    put:
      consumes:
      - application/json
      description: like count increase
      parameters:
      - description: id for project
        in: query
        name: project_id
        required: true
        type: string
      - description: id for user
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: LikeCountIncrease
      tags:
      - Project
  /v1/project/multipleUpload:
    post:
      consumes:
      - multipart/form-data
      description: MultipleUpload
      parameters:
      - description: id for project
        in: query
        name: project_id
        required: true
        type: string
      - description: multiple  file
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: MultipleUpload
      tags:
      - Project
  /v1/user:
    put:
      consumes:
      - application/json
      description: update user basic info
      produces:
      - application/json
      responses: {}
      summary: Update
      tags:
      - User
  /v1/user/callback:
    get:
      consumes:
      - application/json
      description: login success callback
      produces:
      - application/json
      responses: {}
      summary: AuthingCallback
      tags:
      - User
  /v1/user/checkLogin:
    get:
      consumes:
      - application/json
      description: CheckLogin
      produces:
      - application/json
      responses: {}
      summary: CheckLogin
      tags:
      - User
  /v1/user/getCurrentUser:
    get:
      consumes:
      - application/json
      description: 获取用户资料, 在请求的request的header中必须带有accessToken
      produces:
      - application/json
      responses: {}
      summary: GetCurrentUser
      tags:
      - User
swagger: "2.0"
